services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=latte_db
    networks:
      - latte-network
  latte-api:
    container_name: latte-api
    image: manishdait/latte-api:0.0.2
    restart: always
    depends_on:
      - postgres-db
    networks:
      - latte-network
    volumes:
      - data:/app/data
  latte-client:
    container_name: latte-client
    image: manishdait/latte-client:0.0.2
    restart: always
    depends_on:
      - latte-api
    ports:
      - 80:80
    networks:
      - latte-network

volumes:
  pg_data: {}
  data: {}

networks:
  latte-network: