import { 
  faAngleDown,
  faAngleLeft, 
  faAngleRight, 
  faArrowRightToBracket, 
  faCalendar, 
  faCheck, 
  faCircleCheck, 
  faClose, 
  faEllipsisVertical, 
  faEye, 
  faEyeSlash,  
  faHouse,  
  faLock, 
  faPlus,
  faTicketSimple, 
  faGear,
  IconDefinition, 
  faBars,
  faLockOpen,
  faEllipsis
} from '@fortawesome/free-solid-svg-icons'

export const fontawsomeIcons: IconDefinition[] = [
  faHouse, 
  faClose, 
  faPlus,
  faTicketSimple, 
  faAngleRight, 
  faAngleLeft, 
  faLockOpen, 
  faLock, 
  faCalendar, 
  faCheck,
  faGear,
  faBars,
  faEye, 
  faEyeSlash, 
  faAngleDown, 
  faEllipsisVertical,
  faEllipsis, 
  faCircleCheck, 
  faArrowRightToBracket
]