server:
  port: 8080
  
spring:
  profiles:
    active: ${PROFILE:dev}
  application:
    name: latte-api
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
