spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/latte_db
    username: postgres
    password: password
  flyway:
    user: postgres
    password: password

security:
  jwt:
    secret-key: 815F1298534CA2989B84C1C2F48D4609E7A05811E0700653661466A6
    expiration: 7200

latte:
  client-url: http://localhost:4200