CREATE SEQUENCE IF NOT EXISTS notification_seq
START WITH 101
INCREMENT BY 1
MINVALUE 101
MAXVALUE 10000000000
CYCLE;

CREATE TABLE IF NOT EXISTS notification(
  id BIGINT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('notification_seq'),
  message VARCHAR(255) NOT NULL,
  timestamp TIMESTAMP,
  user_id BIGINT REFERENCES _user(id) NOT NULL
);
