CREATE TABLE IF NOT EXISTS smtp_config(
  id INTEGER NOT NULL PRIMARY KEY,
  host VARCHAR(255) NOT NULL,
  port INTEGER NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
