name: Java CI with Maven

on:
  push:
    branches-ignore:
      - release
    paths:
     - latte-api/**
     - .github/**

  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build with Maven
        run: | 
          cd latte-api 
          ./mvnw verify
